language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"

env:
  - AWS_DEFAULT_REGION=us-east-1

# command to install dependencies
install:
  - pip install .
  - pip install -qr requirements.txt

# command to run tests
script: pytest
